# Generated by Django 5.2.16 on 2026-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_service_options_service_examples_service_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Compétence', 'verbose_name_plural': 'Compétences'},
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('development', 'Développement logiciel & Web'), ('database', 'Bases de données'), ('architecture', "Architecture & Systèmes d'information"), ('project', 'Gestion de projets IT'), ('security', 'Sécurité informatique'), ('infrastructure', 'Infrastructure & Administration IT')], default='development', max_length=30, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='skill',
            name='category_type',
            field=models.CharField(choices=[('technical', 'Compétence technique'), ('managerial', 'Compétence managériale')], default='technical', max_length=20, verbose_name='Type de compétence'),
        ),
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='fa-code', help_text='Exemple : fa-python, fa-database, fa-shield-halved', max_length=50, verbose_name='Icône Font Awesome'),
        ),
        migrations.AddField(
            model_name='skill',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Compétence'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='percentage',
            field=models.PositiveIntegerField(verbose_name='Niveau de maîtrise (%)'),
        ),
    ]
