# Generated by Django 5.2.16 on 2026-08-13 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_skill_options_skill_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Technologie', 'verbose_name_plural': 'Technologies'},
        ),
        migrations.AddField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('development', 'Développement'), ('database', 'Bases de données'), ('architecture', 'Architecture & SI'), ('project', 'Gestion de projets'), ('security', 'Sécurité'), ('infrastructure', 'Infrastructure')], default='development', max_length=30, verbose_name='Domaine'),
        ),
        migrations.AddField(
            model_name='technology',
            name='icon',
            field=models.CharField(default='fa-code', help_text='Exemple : fa-python, fa-database, fa-github', max_length=50, verbose_name='Icône Font Awesome'),
        ),
        migrations.AddField(
            model_name='technology',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Technologie'),
        ),
    ]
