# Generated by Django 5.2.16 on 2026-08-14 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_technology_options_technology_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-featured', 'order', '-created_at'], 'verbose_name': 'Projet', 'verbose_name_plural': 'Projets'},
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('web', 'Développement Web'), ('software', 'Développement Logiciel'), ('information_system', "Systèmes d'Information"), ('management', 'Management & Gestion'), ('data', 'Data & Bases de Données'), ('social', 'Innovation Sociale')], default='web', max_length=30, verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False, verbose_name='Projet mis en avant'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage"),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, max_length=200, verbose_name='Mon rôle'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Terminé'), ('ongoing', 'En cours'), ('planned', 'À venir')], default='ongoing', max_length=20, verbose_name='Statut'),
        ),
        migrations.AddField(
            model_name='project',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Année du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, verbose_name='Lien de démonstration'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, verbose_name='Lien GitHub'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='projects/', verbose_name='Image du projet'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', to='website.technology', verbose_name='Technologies'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Nom du projet'),
        ),
    ]
